apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodejs-application-dev
  namespace: flux-system
spec:
  interval: 30s
  path: ./overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomize
  targetNamespace: app-dev
  wait: true