apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-helm-release
  namespace: flux-system
spec:
  interval: 30s
  path: ./helm-releases/grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomize
  targetNamespace: grafana
  wait: true
  postBuild:
    substitute: {}
  patches:
    - patch: |-
        - op: replace
          path: /metadata/name
          value: grafana
        - op: replace
          path: /metadata/namespace
          value: grafana
      target:
        kind: HelmRelease
        name: grafana 