apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 30s
  path: ./helm-releases/grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomize
  targetNamespace: grafana
  wait: true 