apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-releases
  namespace: flux-system
spec:
  interval: 30s
  path: ./helm-releases
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomize
  wait: true 