apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m
  path: ./namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomize
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-releases
  namespace: flux-system
spec:
  interval: 1m
  path: ./helm-releases
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomize
  wait: true
  timeout: 10m
  dependsOn:
    - name: infrastructure 