apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 30s
  path: helm-releases/nginx.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomize
  targetNamespace: nginx
  wait: true