apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rabbitmq
  namespace: flux-system
spec:
  interval: 30s
  path: ./helmreleases
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomize
  targetNamespace: rabbitmq
  wait: true 