apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-application
  namespace: app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-application
  template:
    spec:
      containers:
      - name: nodejs-application
        env:
        - name: ENVIRONMENT
          value: Development