apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-application
  namespace: nodejs-app-dev
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: nodejs-application
        env:
        - name: ENVIRONMENT
          value: Development