apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nodejs-application-dev

namespace: app-dev

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: nodejs-application
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: app-base

configMapGenerator:
  - name: nodejs-application
    files:
      - configs/cm-config.json

images:
  - name: valeriivasianovych/nodejs-example-app
    newTag: v1

nameSuffix: -dev

labels:
  - pairs:
      team: saas-dev
      environment: development
      version: dev

commonAnnotations:
  id: dev-1.1.0
  environment: development
  description: "Development environment configuration"