apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  interval: 10m
  chart:
    spec:
      chart: rabbitmq
      version: ">=12.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  values:
    auth:
      username: user
      password: changeme
    replicaCount: 1