apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/automated-drift-detection: "true"
spec:
  interval: 10s
  releaseName: nginx
  chart:
    spec:
      chart: ingress-nginx
      version: "4.7.1"
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
