apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-kustomize
  namespace: flux-system
spec:
  interval: 15s
  url: https://github.com/ValeriiVasianovych/flux-kustomize
  ref:
    branch: main
