apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: helm-charts
  namespace: flux-system
spec:
  interval: 1m
  chart: helm/
  sourceRef:
    kind: GitRepository
    name: flux-kustomize
    namespace: flux-system 