apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodejs-application-prod
  namespace: flux-system
spec:
  interval: 30s
  path: ./overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomize
  targetNamespace: nodejs-app-prod
  wait: true
