apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  interval: 1m
  chart: helm/rabbitmq
  version: "*"
  sourceRef:
    kind: GitRepository
    name: flux-kustomize
    namespace: flux-system