apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: "9.2.10"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    adminPassword: admin
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      size: 10Gi 