apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/automated-drift-detection: "true"
spec:
  interval: 10s
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: "9.2.10"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system