apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nodejs-application-prod

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: nodejs-application

configMapGenerator:
  - name: nodejs-application
    files:
      - configs/cm-config.json

images:
  - name: valeriivasianovych/nodejs-example-app
    newTag: v2

nameSuffix: -prod
namespace: nodejs-app-prod

labels:
  - pairs:
      team: saas-prod
      environment: production
      version: prod

commonAnnotations:
  id: prod-2.1.0
  environment: production
  description: "Production environment configuration"
