apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-application
  namespace: nodejs-app-prod
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nodejs-application
  template:
    spec:
      containers:
      - name: nodejs-application
        env:
        - name: ENVIRONMENT
          value: Production 