apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nodejs-application-base

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

labels:
  - pairs:
      app: nodejs-application
      team: saas
      deployed-by: kustomize
      owner: valeriivasianovych
      version: base

commonAnnotations:
  owner: valeriivasianovych
  description: "Base configuration for NodeJS application"