resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

labels:
  - pairs:
      app: node-app
      team: saas
      deployed-by: kustomize

commonAnnotations:
  owner: valeriivasianovych