apiVersion: v1
kind: Service
metadata:
  name: nodejs-application
spec:
  selector:
    app: nodejs-application
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  type: ClusterIP
